// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PyotectoProfesionalizante___Resto;

namespace PyotectoProfesionalizante___Resto.Migrations
{
    [DbContext(typeof(RestoContext))]
    [Migration("20220617202559_CreateRestauranteDB")]
    partial class CreateRestauranteDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PyotectoProfesionalizante___Resto.Comensal", b =>
                {
                    b.Property<int>("IdComensal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroCelular")
                        .HasColumnType("int");

                    b.Property<int?>("ReservaIdReserva")
                        .HasColumnType("int");

                    b.Property<string>("RestauranteIdResto")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdComensal");

                    b.HasIndex("ReservaIdReserva");

                    b.HasIndex("RestauranteIdResto");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PyotectoProfesionalizante___Resto.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("EstadoM")
                        .HasColumnType("int");

                    b.Property<string>("RestauranteIdResto")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdMesa");

                    b.HasIndex("RestauranteIdResto");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("PyotectoProfesionalizante___Resto.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstadoR")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("MesasReservadas")
                        .HasColumnType("int");

                    b.Property<string>("RestauranteIdResto")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdReserva");

                    b.HasIndex("RestauranteIdResto");

                    b.ToTable("RegistroReservas");
                });

            modelBuilder.Entity("PyotectoProfesionalizante___Resto.Restaurante", b =>
                {
                    b.Property<string>("IdResto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdResto");

                    b.ToTable("Resto");
                });

            modelBuilder.Entity("PyotectoProfesionalizante___Resto.Comensal", b =>
                {
                    b.HasOne("PyotectoProfesionalizante___Resto.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaIdReserva");

                    b.HasOne("PyotectoProfesionalizante___Resto.Restaurante", null)
                        .WithMany("Clientes")
                        .HasForeignKey("RestauranteIdResto");
                });

            modelBuilder.Entity("PyotectoProfesionalizante___Resto.Mesa", b =>
                {
                    b.HasOne("PyotectoProfesionalizante___Resto.Restaurante", null)
                        .WithMany("Mesas")
                        .HasForeignKey("RestauranteIdResto");
                });

            modelBuilder.Entity("PyotectoProfesionalizante___Resto.Reserva", b =>
                {
                    b.HasOne("PyotectoProfesionalizante___Resto.Restaurante", null)
                        .WithMany("RegistroReservas")
                        .HasForeignKey("RestauranteIdResto");
                });
#pragma warning restore 612, 618
        }
    }
}
